### ISSUE TITLE
Default project doesn't handle an invalid project exception correctly

### ISSUE THREAD

**Issue by remoford** [starfys/timechange#22]
- workaround delete old project directory
Using TensorFlow backend.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\remof\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "C:\Users\remof\Desktop\timechange-demo\timechange\timechange\gui.py", line 29, in defaultProject
    self.parent.tc = timechange.TimeChange()
  File "C:\Users\remof\Desktop\timechange-demo\timechange\timechange\__init__.py", line 129, in __init__
    path.join(self.project_path, "parameters.conf")))
Exception: C:\Users\remof\timechange\default cannot be a timechange project because C:\Users\remof\timechange\default\parameters.conf does not exist

**Comment by lukexorz** [comment]
i am having trouble reproducing this, is it when you load an invalid directory with the Load Existing Project button? Because that seems to be handled successfully

**Comment by remoford** [comment]
No, I think this happens when the default directory is bogus.

**Comment by lukexorz** [comment]
added handling and error message to this issue
