### ISSUE TITLE
Train button crashes

### ISSUE THREAD

**Issue by remoford** [starfys/timechange#31]
I thought steven already fixed this on sunday!
the same multithreading problem we discussed before?
 - workaround this is fatal and there is no workaround
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\remof\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "C:\Users\remof\Desktop\timechange-demo\timechange\timechange\gui.py", line 278, in train_in_thread
    training_results = self.parent.tc.train()
  File "C:\Users\remof\Desktop\timechange-demo\timechange\timechange\__init__.py", line 287, in train
    if self.model is None:
AttributeError: 'TimeChange' object has no attribute 'model'

**Comment by starfys** [comment]
Fixed this in #57 by implementing error popups
