### ISSUE TITLE
Generate FFT crashes

### ISSUE THREAD

**Issue by remoford** [starfys/timechange#33]
Using TensorFlow backend.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\remof\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "C:\Users\remof\Desktop\timechange-demo\timechange\timechange\gui.py", line 131, in genFFT
    t = Thread(target=self.parent.tc.convert_all_csv, args=(self.parent.ConfigureScreen.method, self.parent.ConfigureScreen.chunksize, self.parent.ConfigureScreen.fftsize))
AttributeError: 'ConfigureScreen' object has no attribute 'method'
note - chandu is fixin right now

**Comment by remoford** [comment]
Chandu fixed it
